# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b4f686a2c99d843fa4a1491c93029e220bfac90dcb92349d15730749448b8eb206aa66baeb027e11f16f8e479d8ad2b9c02ec33c9684e016edc04651b16cfb6

test:
  secret_key_base: eb1d07f817a0d405d77e024ed1857881175be8bb0cb5af4bde112c7416694cba00ac3f9d63ac41b20e224228819696d085e1779866ff18ed0ecba4112e5fc633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
